# Generated by Django 5.2.7 on 2026-06-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="fulfilling_facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_requests",
                to="users.facility",
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blood_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requesting_facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_requests",
                to="users.facility",
            ),
        ),
        migrations.AddField(
            model_name="bloodrequeststatusevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequeststatusevent",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="inventory.bloodrequest",
            ),
        ),
        migrations.AddField(
            model_name="bloodunit",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_units",
                to="users.facility",
            ),
        ),
    ]
