# Generated by Django 5.2.7 on 2026-06-17 15:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_REQUEST", "New blood request"),
                            ("REQUEST_ACCEPTED", "Request accepted"),
                            ("REQUEST_REJECTED", "Request rejected"),
                            ("REQUEST_IN_TRANSIT", "Request in transit"),
                            ("REQUEST_FULFILLED", "Request fulfilled"),
                            ("REQUEST_CANCELLED", "Request cancelled"),
                            ("LOW_STOCK", "Low stock alert"),
                            ("EXPIRING_SOON", "Units expiring soon"),
                        ],
                        default="NEW_REQUEST",
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dispatched", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "delivered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
            },
        ),
    ]
