# Generated by Django 5.2.7 on 2025-10-19 06:51

import random
from datetime import timedelta
from django.db import migrations
from django.utils import timezone

# --- CONFIGURATION ---

# Updated list of Ethiopian hospitals with the new location structure.
HOSPITAL_DATA = [
    {
        "name": "Black Lion Specialized Hospital",
        "region": "Addis Ababa",
        "zone": "Lideta Sub-City",
        "woreda": 3,
        "latitude": 9.0132,
        "longitude": 38.7617,
    },
    {
        "name": "Adama Hospital Medical College",
        "region": "Oromia",
        "zone": "East Shewa",
        "woreda": 5,  # Example Woreda
        "latitude": 8.5447,
        "longitude": 39.2721,
    },
    {
        "name": "Gondar University Specialized Hospital",
        "region": "Amhara",
        "zone": "Central Gondar",
        "woreda": 2,  # Example Woreda
        "latitude": 12.6000,
        "longitude": 37.4667,
    },
    {
        "name": "Hawassa University Comprehensive Specialized Hospital",
        "region": "Sidama",  # Hawassa is now in the Sidama region
        "zone": "Hawassa",
        "woreda": 1,  # Example Woreda
        "latitude": 7.0500,
        "longitude": 38.4667,
    },
    {
        "name": "Ayder Comprehensive Specialized Hospital",
        "region": "Tigray",
        "zone": "Mekelle",
        "woreda": 4,  # Example Woreda
        "latitude": 13.4900,
        "longitude": 39.4768,
    },
]

# Approximate blood type distribution percentages (weights) for realistic data.
BLOOD_TYPE_DISTRIBUTION = {
    "A+": 34,
    "A-": 6,
    "B+": 9,
    "B-": 2,
    "AB+": 3,
    "AB-": 1,
    "O+": 38,
    "O-": 7,
}

# --- MIGRATION FUNCTIONS ---


def seed_data(apps, schema_editor):
    """
    Seeds the database with Facility and BloodUnit data using the new
    location structure and a realistic distribution of blood types.
    """
    Facility = apps.get_model("users", "Facility")
    BloodUnit = apps.get_model("inventory", "BloodUnit")

    blood_types = list(BLOOD_TYPE_DISTRIBUTION.keys())
    weights = list(BLOOD_TYPE_DISTRIBUTION.values())

    print("\nSeeding realistic facility and blood unit data...")
    for data in HOSPITAL_DATA:
        # get_or_create checks based on the 'name' field to avoid duplicates
        facility, created = Facility.objects.get_or_create(
            name=data["name"], defaults=data
        )
        if not created:
            print(f"  - Facility '{facility.name}' already exists. Skipping.")
            continue

        print(f"  - Created facility: {facility.name}")

        units_to_create = []
        total_units_for_facility = random.randint(150, 500)

        for _ in range(total_units_for_facility):
            chosen_blood_type = random.choices(blood_types, weights=weights, k=1)[0]
            expiry_date = (
                timezone.now() + timedelta(days=random.randint(1, 42))
            ).date()

            units_to_create.append(
                BloodUnit(
                    blood_type=chosen_blood_type,
                    facility=facility,
                    expires_at=expiry_date,
                )
            )

        BloodUnit.objects.bulk_create(units_to_create)
        print(
            f"    - Seeded {len(units_to_create)} blood units with realistic distribution."
        )


def unseed_data(apps, schema_editor):
    """
    Reverses the seeding, removing the data created by this migration.
    """
    Facility = apps.get_model("users", "Facility")
    facility_names = [data["name"] for data in HOSPITAL_DATA]
    facilities_to_delete = Facility.objects.filter(name__in=facility_names)
    count = facilities_to_delete.count()
    if count > 0:
        facilities_to_delete.delete()
        print(
            f"\nUnseeded and removed {count} facilities and their associated blood units."
        )
    else:
        print("\nNo seeded facilities found to remove.")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),  # Adjust if your user migration is named differently
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=unseed_data),
    ]
