# Generated by Django 5.2.7 on 2025-10-19 06:51

import random
from datetime import timedelta
from django.db import migrations
from django.utils import timezone

# --- CONFIGURATION ---

# Updated list of Ethiopian hospitals with the new location structure.
HOSPITAL_DATA = [
    {
        "name": "Black Lion Specialized Hospital",
        "region": "Addis Ababa",
        "zone": "Lideta Sub-City",
        "woreda": 3,
        "latitude": 9.0132,
        "longitude": 38.7617,
    },
    {
        "name": "Adama Hospital Medical College",
        "region": "Oromia",
        "zone": "East Shewa",
        "woreda": 5,  # Example Woreda
        "latitude": 8.5447,
        "longitude": 39.2721,
    },
    {
        "name": "Gondar University Specialized Hospital",
        "region": "Amhara",
        "zone": "Central Gondar",
        "woreda": 2,  # Example Woreda
        "latitude": 12.6000,
        "longitude": 37.4667,
    },
    {
        "name": "Hawassa University Comprehensive Specialized Hospital",
        "region": "Sidama",  # Hawassa is now in the Sidama region
        "zone": "Hawassa",
        "woreda": 1,  # Example Woreda
        "latitude": 7.0500,
        "longitude": 38.4667,
    },
    {
        "name": "Ayder Comprehensive Specialized Hospital",
        "region": "Tigray",
        "zone": "Mekelle",
        "woreda": 4,  # Example Woreda
        "latitude": 13.4900,
        "longitude": 39.4768,
    },
]

# Approximate blood type distribution percentages (weights) for realistic data.
BLOOD_TYPE_DISTRIBUTION = {
    "A+": 34,
    "A-": 6,
    "B+": 9,
    "B-": 2,
    "AB+": 3,
    "AB-": 1,
    "O+": 38,
    "O-": 7,
}

# --- MIGRATION FUNCTIONS ---


def seed_data(apps, schema_editor):
    """
    Previously this migration seeded realistic data which slowed test runs.
    Moving heavy seeding into `manage.py seed_dev_data` makes migrations
    lightweight and deterministic. Run the management command in development
    to populate facilities and blood units.
    """
    print("Seed step intentionally no-op. Run `manage.py seed_dev_data` to populate dev data.")


def unseed_data(apps, schema_editor):
    """
    Reverses the seeding, removing the data created by this migration.
    """
    Facility = apps.get_model("users", "Facility")
    facility_names = [data["name"] for data in HOSPITAL_DATA]
    facilities_to_delete = Facility.objects.filter(name__in=facility_names)
    count = facilities_to_delete.count()
    if count > 0:
        facilities_to_delete.delete()
        print(
            f"\nUnseeded and removed {count} facilities and their associated blood units."
        )
    else:
        print("\nNo seeded facilities found to remove.")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),  # Adjust if your user migration is named differently
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=unseed_data),
    ]
