"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# This makes sure our 'apps' folder is discoverable
sys.path.insert(0, str(BASE_DIR / "apps"))

# Initialize & Read environmental variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_extensions",
    "django_filters",
    "core",
    "users",
    "inventory",
    "notifications",
    "donations",
    "audit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves static files directly from the app container in
    # production. It must sit immediately after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS must run before any middleware that can generate a response
    # (in particular CommonMiddleware) so preflight requests are answered
    # and CORS headers are attached to every response (ADR-0009).
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Allauth Middleware
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # SRS VBB-FUN-UM-002 / NFR-SEC-004: minimum 8 characters.
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        # SRS NFR-SEC-004: enforce upper/lower/digit/special character complexity.
        "NAME": "core.validators.PasswordComplexityValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # The mobile client authenticates with JWTs (SDS 2.3.3). Session auth is
        # retained so the Django admin and the browsable API keep working.
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "core.permissions.PasswordChangeNotRequired",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    # Baseline API rate limits (ADR-0009). The "auth" scope is applied to the
    # login view to slow down credential-stuffing attempts.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env.str("THROTTLE_ANON_RATE", default="60/min"),
        "user": env.str("THROTTLE_USER_RATE", default="240/min"),
        "auth": env.str("THROTTLE_AUTH_RATE", default="10/min"),
    },
}

# --- SIMPLE JWT (SDS 2.3.3) -------------------------------------------------
# Access token lifetime maps to the SRS 30-minute inactivity logout
# (VBB-FUN-UM-005); refresh lifetime maps to the 7-day "Remember Me"
# (VBB-FUN-UM-007). Token claims carry the role and facility so the API gateway
# can enforce the RBAC permission matrix without a DB lookup.
# Refresh tokens rotate on every use and the used token is blacklisted
# (ADR-0009), so a stolen refresh token stops working after the legitimate
# client refreshes; logout blacklists the current refresh token explicitly.
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

AUTH_USER_MODEL = "users.User"

# --- ALLAUTH & API SETTINGS ---

# 1. FRONTEND CONFIGURATION
# ------------------------------------------------------------------------------
# The base URL of your React/Vue/etc. frontend application
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# --- CORS (ADR-0009) --------------------------------------------------------
# The web client is served from a different origin than the API, so browsers
# need explicit CORS grants. Origins are env-driven and default to none;
# dev.py adds the Vite dev server. CORS_ALLOW_ALL_ORIGINS is deliberately
# never enabled.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

# These are the URLs that Django will generate in emails (e.g., for verification).
# Your frontend application MUST have routes that can handle these URLs.
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_URL}/verify-email/{{key}}",
    "account_reset_password_from_key": f"{FRONTEND_URL}/forgot-password/{{key}}",
    "account_signup": f"{FRONTEND_URL}/signup",
    "socialaccount_login_error": f"{FRONTEND_URL}/login",
    "account_reset_password": f"{FRONTEND_URL}/forgot-password",
}

# 2. ALLAUTH CONFIGURATION
# ------------------------------------------------------------------------------
# Required for allauth to work
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Authenticate by email or Ethiopian phone number (SRS VBB-FUN-UM-004).
    "users.auth_backends.EmailOrPhoneBackend",
    "django.contrib.auth.backends.ModelBackend",  # default
    "allauth.account.auth_backends.AuthenticationBackend",  # allauth
]

# Prevents html templates from being accessed and sent
HEADLESS_ONLY = True

# Basic account setup
ACCOUNT_SIGNUP_FORM_CLASS = "users.forms.CustomSignupAddonForm"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["username", "email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True

# 3. Social Account Settings
# ------------------------------------------------------------------------------
# When attempting to login/signup with a social account, if an email with that
# account, already exists, allow login.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# When attempting to login/signup with a social account, if an email with that
# account already exists connect the provider to that account.
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
# Social Account Providers (e.g., Google)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        # Trust Google to provide a verified email.
        "EMAIL_AUTHENTICATION": True,
        # Automatically connect the Google account to the existing user.
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    },
    "github": {
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID", default=""),
            "secret": env("GITHUB_CLIENT_SECRET", default=""),
        },
        "SCOPE": ["read:user", "user:email"],
        # Trust GitHub to provide a verified email.
        "EMAIL_AUTHENTICATION": True,
        # Automatically connect the GitHub account to the existing user.
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
# Log to stdout so the platform (Render, Docker) captures application logs.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("DJANGO_LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}
