"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# This makes sure our 'apps' folder is discoverable
sys.path.insert(0, str(BASE_DIR / "apps"))

# Initialize & Read environmental variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_extensions",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "drf_standardized_errors",
    "core",
    "users",
    "inventory",
    "notifications",
    "donations",
    "audit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves static files directly from the app container in
    # production. It must sit immediately after SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Allauth Middleware
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # SRS VBB-FUN-UM-002 / NFR-SEC-004: minimum 8 characters.
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        # SRS NFR-SEC-004: enforce upper/lower/digit/special character complexity.
        "NAME": "core.validators.PasswordComplexityValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # The mobile client authenticates with JWTs (SDS 2.3.3). Session auth is
        # retained so the Django admin and the browsable API keep working.
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "core.permissions.PasswordChangeNotRequired",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    # All 4xx/5xx bodies use the drf-standardized-errors envelope
    # ({"type", "errors": [{"code", "detail", "attr"}]}) — see ADR-0010.
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    # drf-standardized-errors' AutoSchema extends drf-spectacular's so every
    # operation also documents its error responses.
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
}

# --- OPENAPI SCHEMA (drf-spectacular, ADR-0010) -----------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Virtual Blood Bank API",
    "VERSION": "1.0.0",
    "DESCRIPTION": (
        "A district-level mHealth system that helps rural Ethiopian health "
        "facilities share blood in real time to reduce maternal mortality "
        "from postpartum hemorrhage."
    ),
    "SERVE_INCLUDE_SCHEMA": False,
    # The schema is not sensitive; the mobile/web teams need it without auth.
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SERVE_AUTHENTICATION": [],
    # Serve Swagger UI assets from the sidecar package (offline-friendly).
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # drf-standardized-errors integration: its enum postprocessing hook skips
    # the dynamically generated *ErrorComponent enums so "attr"/"code" choices
    # shared across serializers don't collide into bogus shared enums.
    "ENUM_NAME_OVERRIDES": {
        # status / from_status / to_status all share the RequestStatus choices;
        # collapse them into one named enum instead of three colliding ones.
        # Keep in sync with inventory.models.BloodRequest.RequestStatus.
        "BloodRequestStatusEnum": [
            ("PENDING", "Pending"),
            ("ACCEPTED", "Accepted"),
            ("REJECTED", "Rejected"),
            ("IN_TRANSIT", "In Transit"),
            ("FULFILLED", "Fulfilled"),
            ("CANCELLED", "Cancelled"),
        ],
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
    "POSTPROCESSING_HOOKS": [
        "drf_standardized_errors.openapi_hooks.postprocess_schema_enums",
    ],
}

# --- SIMPLE JWT (SDS 2.3.3) -------------------------------------------------
# Access token lifetime maps to the SRS 30-minute inactivity logout
# (VBB-FUN-UM-005); refresh lifetime maps to the 7-day "Remember Me"
# (VBB-FUN-UM-007). Token claims carry the role and facility so the API gateway
# can enforce the RBAC permission matrix without a DB lookup.
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

AUTH_USER_MODEL = "users.User"

# --- ALLAUTH & API SETTINGS ---

# 1. FRONTEND CONFIGURATION
# ------------------------------------------------------------------------------
# The base URL of your React/Vue/etc. frontend application
FRONTEND_URL = "http://localhost:5173"

# These are the URLs that Django will generate in emails (e.g., for verification).
# Your frontend application MUST have routes that can handle these URLs.
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_URL}/verify-email/{{key}}",
    "account_reset_password_from_key": f"{FRONTEND_URL}/forgot-password/{{key}}",
    "account_signup": f"{FRONTEND_URL}/signup",
    "socialaccount_login_error": f"{FRONTEND_URL}/login",
    "account_reset_password": f"{FRONTEND_URL}/forgot-password",
}

# 2. ALLAUTH CONFIGURATION
# ------------------------------------------------------------------------------
# Required for allauth to work
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Authenticate by email or Ethiopian phone number (SRS VBB-FUN-UM-004).
    "users.auth_backends.EmailOrPhoneBackend",
    "django.contrib.auth.backends.ModelBackend",  # default
    "allauth.account.auth_backends.AuthenticationBackend",  # allauth
]

# Prevents html templates from being accessed and sent
HEADLESS_ONLY = True

# Basic account setup
ACCOUNT_SIGNUP_FORM_CLASS = "users.forms.CustomSignupAddonForm"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["username", "email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True

# 3. Social Account Settings
# ------------------------------------------------------------------------------
# When attempting to login/signup with a social account, if an email with that
# account, already exists, allow login.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# When attempting to login/signup with a social account, if an email with that
# account already exists connect the provider to that account.
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
# Social Account Providers (e.g., Google)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        # Trust Google to provide a verified email.
        "EMAIL_AUTHENTICATION": True,
        # Automatically connect the Google account to the existing user.
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    },
    "github": {
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID", default=""),
            "secret": env("GITHUB_CLIENT_SECRET", default=""),
        },
        "SCOPE": ["read:user", "user:email"],
        # Trust GitHub to provide a verified email.
        "EMAIL_AUTHENTICATION": True,
        # Automatically connect the GitHub account to the existing user.
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
# Log to stdout so the platform (Render, Docker) captures application logs.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("DJANGO_LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}
