from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer

from core.validators import generate_temp_password

from ..models import Facility, User


class FacilitySerializer(serializers.ModelSerializer):
    class Meta:
        model = Facility
        fields = [
            "id",
            "name",
            "region",
            "zone",
            "woreda",
            "street",
            "city",
            "latitude",
            "longitude",
            "contact_phone",
            "is_active",
        ]


class UserSerializer(serializers.ModelSerializer):
    """Read/representation serializer for users."""

    facility = serializers.PrimaryKeyRelatedField(
        queryset=Facility.objects.all(), allow_null=True
    )

    class Meta:
        model = User
        fields = [
            "id",
            "username",
            "email",
            "full_name",
            "phone_number",
            "role",
            "facility",
            "is_active",
            "must_change_password",
            "last_login",
            "date_joined",
        ]
        read_only_fields = [
            "is_active",
            "must_change_password",
            "last_login",
            "date_joined",
        ]


class AdminUserCreateSerializer(serializers.ModelSerializer):
    """Admin-side user provisioning (SRS VBB-FUN-UM-001, UC-006).

    A temporary password is supplied (or generated by the view) and the new
    user must rotate it on first login.
    """

    password = serializers.CharField(write_only=True, required=False)

    class Meta:
        model = User
        fields = [
            "id",
            "username",
            "email",
            "full_name",
            "phone_number",
            "role",
            "facility",
            "password",
        ]

    def create(self, validated_data):
        password = validated_data.pop("password", None) or generate_temp_password()
        user = User(**validated_data)
        user.set_password(password)
        user.must_change_password = True
        user.save()
        # Surface the generated temp password once so the admin can relay it.
        user._temporary_password = password
        return user


class RoleAssignmentSerializer(serializers.Serializer):
    role = serializers.ChoiceField(choices=User.Role.choices)


class ProfileSerializer(serializers.ModelSerializer):
    """Self-service profile view/update (SRS VBB-FUN-UM-011/012)."""

    class Meta:
        model = User
        fields = [
            "id",
            "username",
            "email",
            "full_name",
            "phone_number",
            "role",
            "facility",
            "must_change_password",
        ]
        read_only_fields = [
            "id",
            "username",
            "email",
            "role",
            "facility",
            "must_change_password",
        ]


class ChangePasswordSerializer(serializers.Serializer):
    current_password = serializers.CharField(write_only=True)
    new_password = serializers.CharField(write_only=True)

    def validate_current_password(self, value):
        user = self.context["request"].user
        if not user.check_password(value):
            raise serializers.ValidationError("Current password is incorrect.")
        return value

    def validate_new_password(self, value):
        validate_password(value, user=self.context["request"].user)
        return value


class EmailOrPhoneTokenSerializer(TokenObtainPairSerializer):
    """JWT obtain serializer keyed on email/phone, with role/facility claims.

    The ``username`` field accepts an email, phone number, or username; the
    configured ``EmailOrPhoneBackend`` resolves it (SRS VBB-FUN-UM-004). Token
    claims carry ``role`` and ``facility_id`` so the API can enforce the RBAC
    matrix without a DB lookup (SDS 2.3.3).
    """

    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)
        token["role"] = user.role
        token["facility_id"] = str(user.facility_id) if user.facility_id else None
        token["full_name"] = user.full_name
        token["must_change_password"] = user.must_change_password
        return token
